[store.primary]
  connection = "postgresql://postgres:let-me-in@postgres/subgraph?sslmode=prefer"
  weight = 1
  pool_size = 10

[chains]
  ingestor = "index_node"
  [chains.mainnet]
    shard = "primary"
    [[chains.mainnet.provider]]
      label = "mainnet"
      # 这里需要替换成自己的api-key
      url = "https://ethereum-mainnet.s.chainbase.online/v1/<api-key>"
      features = ["archive","traces"]
      transport = "rpc"

  [chains.base]
    shard = "primary"
    [[chains.base.provider]]
      label = "base"
      # 这里需要替换成自己的api-key
      url = "https://base-mainnet.s.chainbase.com/v1/<api-key>"
      features = ["archive","traces"]
      transport = "rpc"

[deployment]
[[deployment.rule]]
  shard = "primary"
  indexers = [ "index_node" ]